//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edicas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TienditaEntities : DbContext
    {
        public TienditaEntities()
            : base("name=TienditaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Proveedore> Proveedores { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual int sp_A_Producto(string proNombre, Nullable<int> proCantidad, Nullable<decimal> proPrecio, byte[] proImagen, Nullable<int> iDCategoria, string rUC)
        {
            var proNombreParameter = proNombre != null ?
                new ObjectParameter("proNombre", proNombre) :
                new ObjectParameter("proNombre", typeof(string));
    
            var proCantidadParameter = proCantidad.HasValue ?
                new ObjectParameter("proCantidad", proCantidad) :
                new ObjectParameter("proCantidad", typeof(int));
    
            var proPrecioParameter = proPrecio.HasValue ?
                new ObjectParameter("proPrecio", proPrecio) :
                new ObjectParameter("proPrecio", typeof(decimal));
    
            var proImagenParameter = proImagen != null ?
                new ObjectParameter("proImagen", proImagen) :
                new ObjectParameter("proImagen", typeof(byte[]));
    
            var iDCategoriaParameter = iDCategoria.HasValue ?
                new ObjectParameter("IDCategoria", iDCategoria) :
                new ObjectParameter("IDCategoria", typeof(int));
    
            var rUCParameter = rUC != null ?
                new ObjectParameter("RUC", rUC) :
                new ObjectParameter("RUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_A_Producto", proNombreParameter, proCantidadParameter, proPrecioParameter, proImagenParameter, iDCategoriaParameter, rUCParameter);
        }
    
        public virtual int sp_E_Producto(Nullable<int> iDProducto)
        {
            var iDProductoParameter = iDProducto.HasValue ?
                new ObjectParameter("IDProducto", iDProducto) :
                new ObjectParameter("IDProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_E_Producto", iDProductoParameter);
        }
    
        public virtual ObjectResult<sp_C_Productos_Result> sp_C_Productos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_C_Productos_Result>("sp_C_Productos");
        }
    
        public virtual ObjectResult<sp_C_ProductoxID_Result> sp_C_ProductoxID(Nullable<int> iDProducto)
        {
            var iDProductoParameter = iDProducto.HasValue ?
                new ObjectParameter("IDProducto", iDProducto) :
                new ObjectParameter("IDProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_C_ProductoxID_Result>("sp_C_ProductoxID", iDProductoParameter);
        }
    
        public virtual int sp_M_Producto(Nullable<int> iDProducto, string proNombre, Nullable<int> proCantidad, Nullable<decimal> proPrecio, byte[] proImagen, Nullable<int> iDCategoria, string rUC)
        {
            var iDProductoParameter = iDProducto.HasValue ?
                new ObjectParameter("IDProducto", iDProducto) :
                new ObjectParameter("IDProducto", typeof(int));
    
            var proNombreParameter = proNombre != null ?
                new ObjectParameter("proNombre", proNombre) :
                new ObjectParameter("proNombre", typeof(string));
    
            var proCantidadParameter = proCantidad.HasValue ?
                new ObjectParameter("proCantidad", proCantidad) :
                new ObjectParameter("proCantidad", typeof(int));
    
            var proPrecioParameter = proPrecio.HasValue ?
                new ObjectParameter("proPrecio", proPrecio) :
                new ObjectParameter("proPrecio", typeof(decimal));
    
            var proImagenParameter = proImagen != null ?
                new ObjectParameter("proImagen", proImagen) :
                new ObjectParameter("proImagen", typeof(byte[]));
    
            var iDCategoriaParameter = iDCategoria.HasValue ?
                new ObjectParameter("IDCategoria", iDCategoria) :
                new ObjectParameter("IDCategoria", typeof(int));
    
            var rUCParameter = rUC != null ?
                new ObjectParameter("RUC", rUC) :
                new ObjectParameter("RUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_M_Producto", iDProductoParameter, proNombreParameter, proCantidadParameter, proPrecioParameter, proImagenParameter, iDCategoriaParameter, rUCParameter);
        }
    
        public virtual int sp_A_Proveedor(string rUC, string provNombre, string provDireccion, string provTelefono)
        {
            var rUCParameter = rUC != null ?
                new ObjectParameter("RUC", rUC) :
                new ObjectParameter("RUC", typeof(string));
    
            var provNombreParameter = provNombre != null ?
                new ObjectParameter("provNombre", provNombre) :
                new ObjectParameter("provNombre", typeof(string));
    
            var provDireccionParameter = provDireccion != null ?
                new ObjectParameter("provDireccion", provDireccion) :
                new ObjectParameter("provDireccion", typeof(string));
    
            var provTelefonoParameter = provTelefono != null ?
                new ObjectParameter("provTelefono", provTelefono) :
                new ObjectParameter("provTelefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_A_Proveedor", rUCParameter, provNombreParameter, provDireccionParameter, provTelefonoParameter);
        }
    
        public virtual ObjectResult<sp_C_Proveedores_Result> sp_C_Proveedores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_C_Proveedores_Result>("sp_C_Proveedores");
        }
    
        public virtual ObjectResult<sp_C_ProveedorxRUC_Result> sp_C_ProveedorxRUC(string rUC)
        {
            var rUCParameter = rUC != null ?
                new ObjectParameter("RUC", rUC) :
                new ObjectParameter("RUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_C_ProveedorxRUC_Result>("sp_C_ProveedorxRUC", rUCParameter);
        }
    
        public virtual int sp_E_Proveedor(string rUC)
        {
            var rUCParameter = rUC != null ?
                new ObjectParameter("RUC", rUC) :
                new ObjectParameter("RUC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_E_Proveedor", rUCParameter);
        }
    
        public virtual int sp_M_Proveedor(string rUC, string provNombre, string provDireccion, string provTelefono)
        {
            var rUCParameter = rUC != null ?
                new ObjectParameter("RUC", rUC) :
                new ObjectParameter("RUC", typeof(string));
    
            var provNombreParameter = provNombre != null ?
                new ObjectParameter("provNombre", provNombre) :
                new ObjectParameter("provNombre", typeof(string));
    
            var provDireccionParameter = provDireccion != null ?
                new ObjectParameter("provDireccion", provDireccion) :
                new ObjectParameter("provDireccion", typeof(string));
    
            var provTelefonoParameter = provTelefono != null ?
                new ObjectParameter("provTelefono", provTelefono) :
                new ObjectParameter("provTelefono", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_M_Proveedor", rUCParameter, provNombreParameter, provDireccionParameter, provTelefonoParameter);
        }
    
        public virtual int sp_A_Usuario(string usuEmail, string usuContraseña, string usuNombre, Nullable<int> iDRol)
        {
            var usuEmailParameter = usuEmail != null ?
                new ObjectParameter("usuEmail", usuEmail) :
                new ObjectParameter("usuEmail", typeof(string));
    
            var usuContraseñaParameter = usuContraseña != null ?
                new ObjectParameter("usuContraseña", usuContraseña) :
                new ObjectParameter("usuContraseña", typeof(string));
    
            var usuNombreParameter = usuNombre != null ?
                new ObjectParameter("usuNombre", usuNombre) :
                new ObjectParameter("usuNombre", typeof(string));
    
            var iDRolParameter = iDRol.HasValue ?
                new ObjectParameter("IDRol", iDRol) :
                new ObjectParameter("IDRol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_A_Usuario", usuEmailParameter, usuContraseñaParameter, usuNombreParameter, iDRolParameter);
        }
    
        public virtual ObjectResult<sp_C_Usuario_Result> sp_C_Usuario(string usuEmail, string usuContraseña)
        {
            var usuEmailParameter = usuEmail != null ?
                new ObjectParameter("usuEmail", usuEmail) :
                new ObjectParameter("usuEmail", typeof(string));
    
            var usuContraseñaParameter = usuContraseña != null ?
                new ObjectParameter("usuContraseña", usuContraseña) :
                new ObjectParameter("usuContraseña", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_C_Usuario_Result>("sp_C_Usuario", usuEmailParameter, usuContraseñaParameter);
        }
    }
}
