//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edicas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int IDProducto { get; set; }
        public string proNombre { get; set; }
        public decimal proPrecio { get; set; }
        public int IDCategoria { get; set; }
        public bool proEstado { get; set; }
        public Nullable<int> proCantidad { get; set; }
        public byte[] proImagen { get; set; }
        public string RUC { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Proveedore Proveedore { get; set; }
    }
}
