//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edicas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IDUsuario { get; set; }
        public string usuEmail { get; set; }
        public string usuContraseña { get; set; }
        public string usuNombre { get; set; }
        public Nullable<int> IDRol { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
