//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edicas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Producto
    {
        string mensajeVacio = null;
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetalleIngreso = new HashSet<DetalleIngreso>();
        }
        public int IDProducto { get; set; }
        [Required(ErrorMessage = "El nombre es nesecario")]
        public string proNombre { get; set; }
        [Required (ErrorMessage ="El precio es nesecario")]
        public decimal proPrecioVenta { get; set; }
        public int proCantidad { get; set; }
        public int IDProveedor { get; set; }
        public int IDCategoria { get; set; }
        public bool Estado { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleIngreso> DetalleIngreso { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
